### ISSUE TITLE
LoadSoundMemByMemImage関数がmp3ファイルを正常に読み込まない

### ISSUE THREAD

**Issue by tangeshita** [nokotan/DxLibForHTML5#3]
mp3ファイルのメモリファイルからの読み込みにおいてLoadSoundMemByMemImage関数が正常に読み込まない動作をするようです。（-1を返します）
wavファイルとoggファイルは正常に再生出来ることを確認出来ました。

以下のログが出力されました。
```

5664:音声ファイルのＰＣＭへの変換に失敗しました
```

**Comment by nokotan** [comment]
本家 DX ライブラリでも [MP3 形式の音声ファイルの読み込みは Windows 版のみの機能](https://dxlib.xsrv.jp/dxinfo.html)で、Android 版および iOS 版ではサポートされていません。

音声再生機能は iOS 版のものを使用しているため、HTML5 版で MP3 形式の音声ファイルの読み込みが正常に読み込まれない動作はむしろ期待された動作となります。

ただ、[主要ブラウザではブラウザ側で MP3 形式の音声ファイルのデコード処理を(非同期に)することができる](https://developer.mozilla.org/ja/docs/Web/API/BaseAudioContext/decodeAudioData)ので、これを HTML5 版の拡張機能として実装する可能性はあります。

**Comment by tangeshita** [comment]
返信ありがとうございました。
mp3を使用しないように実装していきます。
